In [ ]:
import numpy as np
#R matrix
R=np.matrix([[-1,-1,-1,-1,0,-1],
             [-1,-1,-1,0,-1,100],
             [-1,-1,-1,0,-1,-1],
             [-1,0,0,-1,0,-1],
             [-1,0,0,-1,-1,100],
             [-1,0,-1,-1,0,100]])



In [ ]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [ ]:
#q matrix
Q=np.matrix(np.zeros([6,6]))
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
gamma=0.8

In [ ]:
initial_state=2

In [ ]:
#this function returns all available actions in the state given as an argument
def available_actions(state):
  current_state_row=R[state,]
  av_act=np.where(current_state_row>=0)[1]
  return av_act

In [ ]:
available_act=available_actions(initial_state)

In [ ]:
available_act

array([3])

In [ ]:
def sample_next_action(available_actions_range):
  next_action=int(np.random.choice(available_act,1))
  return next_action

In [ ]:
action=sample_next_action(available_act)

In [ ]:
action

3

In [ ]:
#this function updates the  Qmatrix according to the path selected and the Q learning algorithm
def update(current_state,action,games):
  max_index=np.where(Q[action,]==np.max(Q[action,]))[1]
                       
  if max_index.shape[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
      max_indexint(max_index)
      max_value=Q[action, max-index]

      Q[current_state,action]=R[current_state,action]+gamma*max_value                     

In [ ]:
update(initial_state,action,gamma)

In [ ]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
#Training
#Train over 10,000 iterations
for i in range(1000):
  current_state=np.random.randint(0,int(Q.shape[0]))
  available_act=available_actions(current_state)
  action=sample_next_action(available_act)
  update(current_state,action,gamma)

In [ ]:
print("Trained Q matrix")
print(Q/np.max(Q)*100)

Trained Q matrix
[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [ ]:
current_state=1
steps=[current_state]

while current_state != 5:
  next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index=int(np.random.choice(next_step_index,size=1))
  else:
    next_step_index=int(next_step_index)

  steps.append(next_step_index)
  current_state=next_step_index
  
        


In [ ]:
print("selected path:")
print(steps)

selected path:
[1, 5]


# New section